[package]
name = "fungoid"
version = "0.1.0"
authors = ["Josh Karpel <josh.karpel@gmail.com>"]
edition = '2018'

[dependencies]
clap = "2.31.2"
rand = "0.7.3"
separator = "0.4.1"
humantime = "2.0.1"
crossterm = "0.17.5"
