name: pre-commit

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  pre-commit:
    strategy:
      fail-fast: false
      matrix:
        toolchain: [ stable ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
      - uses: actions/setup-python@v4.0.0
        with:
          python-version: "3.x"
      - uses: pre-commit/action@v3.0.0
